mode = "dark"

accent = "#fe8019"
selection = "#504945"
muted = "#a89984"

background = "#282828"
dark_background = "#1d2021"
darker_background = "#1d2021"
lighter_background = "#3c3836"

foreground = "#ebdbb2"
dark_foreground = "#a89984"
light_foreground = "#fbf1c7"
bright_foreground = "#fbf1c7"

red = "#fb4934"
yellow = "#fabd2f"
orange = "#fe8019"
green = "#b8bb26"
cyan = "#8ec07c"
blue = "#83a598"
magenta = "#d3869b"
